print("hello \"world\" world")
print('I\'m harshit')
print("line A")
print("line b")
print("line A \nline B\n line C")
print("name\tharshit")
print("this is backlash\\")
print("this is double backlash\\\\")
print("hell\blo")